name: Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
            build_type: Debug
          - cc: gcc
            cxx: g++
            build_type: Release
          - cc: clang
            cxx: clang++
            build_type: Debug
          - cc: clang
            cxx: clang++
            build_type: Release

    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - name: Checkout fcitx5-lekhika repository
        uses: actions/checkout@v4

      - name: Install distro dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            cmake \
            build-essential \
            ninja-build extra-cmake-modules \
            libfcitx5core-dev libfcitx5utils-dev libfcitx5config-dev \
            libsqlite3-dev libicu-dev \
            gettext appstream

      - name: Clone liblekhika dependency
        run: git clone https://github.com/khumnath/liblekhika.git

      - name: Build and Install liblekhika
        run: |
          cd liblekhika
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build build
          sudo cmake --install build

      - name: Update shared library cache
        run: sudo ldconfig

      - name: Test liblekhika-cli transliteration
        run: |
          echo "Testing lekhika-cli transliteration..."
          lekhika-cli transliterate nepaal

      - name: Configure fcitx5-lekhika
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build fcitx5-lekhika
        run: cmake --build build

      - name: Stage install files into dist/ directory
        run: DESTDIR=dist cmake --install build

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.cc }}-${{ matrix.build_type }}
          path: dist/

