name: Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc]
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    env:
      CC:  ${{ matrix.cc }}
      CXX: ${{ matrix.cc == 'gcc' && 'g++' || 'clang++' }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install distro dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build extra-cmake-modules \
            libfcitx5core-dev libfcitx5utils-dev libfcitx5config-dev \
            libsqlite3-dev qt6-base-dev qt6-base-dev-tools libicu-dev \
            gettext appstream

      - name: Configure
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build build

      - name: Stage install files into dist/ directory
        run: DESTDIR=dist cmake --install build

      - name: Upload Release build artefacts
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: linux-all
          path: dist/

  source-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Create source tarball
        run: |
          VER=$(cat version.txt)
          DIR="fcitx5-lekhika-${VER}"
          TAR="${DIR}.tar.gz"

          # Make a copy of repo including submodules
          mkdir "$DIR"
          rsync -a --exclude='.git' ./ "$DIR"/
          tar -czf "$TAR" "$DIR"

      - name: Upload source tarball
        uses: actions/upload-artifact@v4
        with:
          name: source-tarball
          path: '*.tar.gz'
