name: Debian Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          git cmake build-essential ninja-build \
          fcitx5-dev fcitx5-utils-dev libtoml++-dev

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr

    - name: Build
      run: cmake --build build
