name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  source-archive:
    runs-on: ubuntu-latest
    outputs:
      tarball: ${{ steps.src.outputs.tarball }}
      version: ${{ steps.src.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - id: src
        run: |
          VER=${GITHUB_REF_NAME#v}
          TAR="fcitx5-lekhika-${VER}.tar"

          # create main archive
          git archive --format=tar --prefix="fcitx5-lekhika-${VER}/" HEAD > "$TAR"

          # append liblekhika
          (cd liblekhika && git archive --format=tar \
            --prefix="fcitx5-lekhika-${VER}/liblekhika/" HEAD ) >> "$TAR"

          gzip -f "$TAR"
          echo "tarball=$TAR.gz" >> $GITHUB_OUTPUT
          echo "version=$VER" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: source-archive
          path: ${{ steps.src.outputs.tarball }}

  arch:
    runs-on: ubuntu-latest
    needs: source-archive
    container: archlinux:latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-archive

      - name: Install deps
        run: pacman -Syu --noconfirm git base-devel cmake ninja fcitx5-qt sqlite qt6-base icu

      - name: Build Arch package
        run: |
          VER=${GITHUB_REF_NAME#v}
cat > PKGBUILD <<'EOF'
pkgname=fcitx5-lekhika
pkgver=${VER}
pkgrel=1
arch=('x86_64')
url="https://github.com/AksharLabs/fcitx5-lekhika"
license=('GPL')
depends=('fcitx5-qt' 'sqlite' 'icu' 'qt6-base')
makedepends=('cmake' 'ninja')
source=("${pkgname}-${pkgver}.tar.gz")
sha256sums=('SKIP')

build() {
  cd "$srcdir/${pkgname}-${pkgver}"
  cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr
  ninja -C build
}

package() {
  cd "$srcdir/${pkgname}-${pkgver}"
  DESTDIR="$pkgdir" ninja -C build install
}
EOF

          bsdtar -xf fcitx5-lekhika-${VER}.tar.gz
          makepkg -sf --noconfirm

      - uses: actions/upload-artifact@v4
        with:
          name: arch-pkg
          path: "*.pkg.tar.zst"

  fedora:
    runs-on: ubuntu-latest
    needs: source-archive
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4

      - name: Mark repo as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/download-artifact@v4
        with:
          name: source-archive

      - name: Install deps
        run: dnf install -y git-core rpm-build cmake ninja-build gcc-c++ fcitx5-devel qt6-qtbase-devel sqlite-devel libicu-devel

      - name: Build RPM
        run: |
          VER=${GITHUB_REF_NAME#v}
cat > fcitx5-lekhika.spec <<'EOF'
Name:           fcitx5-lekhika
Version:        ${VER}
Release:        1%{?dist}
Summary:        Fcitx5 input method for Nepali
License:        GPL
URL:            https://github.com/AksharLabs/fcitx5-lekhika
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  cmake, ninja-build, gcc-c++, fcitx5-devel, qt6-qtbase-devel, sqlite-devel, libicu-devel

%description
Nepali input method for Fcitx5.

%prep
%setup -q

%build
%cmake -G Ninja
%ninja_build

%install
%ninja_install

%files
%license LICENSE
%doc README.md
/usr/share/*
/usr/lib64/*
/usr/bin/*
EOF

          mv fcitx5-lekhika-${VER}.tar.gz /root/rpmbuild/SOURCES/
          rpmbuild -ba fcitx5-lekhika.spec
          cp /root/rpmbuild/RPMS/x86_64/*.rpm .

      - uses: actions/upload-artifact@v4
        with:
          name: fedora-rpm
          path: "*.rpm"

  ubuntu:
    runs-on: ubuntu-latest
    needs: source-archive
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: source-archive

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential devscripts debhelper cmake ninja-build fcitx5-dev libqt6core5compat6-dev libqt6widgets6 libqt6opengl6-dev libsqlite3-dev libicu-dev

      - name: Patch debian/rules
        run: |
          sed -i '/^%:/a override_dh_auto_install:\n\tdh_auto_install -- DESTDIR=$(CURDIR)/debian/tmp' debian/rules

      - name: Build deb
        run: |
          VER=${GITHUB_REF_NAME#v}
          tar xf fcitx5-lekhika-${VER}.tar.gz
          cd fcitx5-lekhika-${VER}
          debuild -us -uc -b

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-deb
          path: "../*.deb"

  release:
    runs-on: ubuntu-latest
    needs: [source-archive, arch, fedora, ubuntu]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-archive
      - uses: actions/download-artifact@v4
        with:
          name: arch-pkg
      - uses: actions/download-artifact@v4
        with:
          name: fedora-rpm
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-deb

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.pkg.tar.zst
            *.rpm
            *.deb
